FROM ruby:3.0.1
# RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN mkdir /randw
WORKDIR /randw
RUN gem install bundler:2.2
RUN bundle config set force_ruby_platform true
COPY ./docker/sources.list /etc/apt/sources.list
RUN apt-get update -y --allow-insecure-repositories || true
RUN apt-get install -y sudo || true
RUN sudo apt-get install -y less vim || true
COPY ./docker/inputrc /root/.inputrc
COPY ./docker/bash_profile /root/.bash_profile
CMD ["/randw/scripts/runtests.sh"]
